# Generated by Django 4.2 on 2023-07-06 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_author_theme_author_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sub_Theme',
            new_name='SubTheme',
        ),
    ]
