# Generated by Django 4.2 on 2023-07-06 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_sub_theme_subtheme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='sub_theme',
            new_name='subTheme',
        ),
        migrations.RenameField(
            model_name='subtheme',
            old_name='sub_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='note_title',
            new_name='title',
        ),
    ]
