# Generated by Django 4.2 on 2023-07-06 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_sub_theme_note_subtheme_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtheme',
            old_name='main_title',
            new_name='theme',
        ),
    ]
