# Generated by Django 4.2 on 2023-07-06 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_main_title_subtheme_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='subTheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note', to='main.subtheme'),
        ),
    ]
