# Generated by Django 3.2.10 on 2023-10-09 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auth',
        ),
    ]
